"""Remove final_script and is_edited from PodcastTask

Revision ID: 6b75c5b4321d
Revises: ce2e9a10b9d0
Create Date: 2025-06-28 18:52:02.115517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b75c5b4321d'
down_revision: Union[str, Sequence[str], None] = 'ce2e9a10b9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
