"""initial

Revision ID: 7b631d0d5e1c
Revises: 
Create Date: 2025-06-28 18:17:32.525247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b631d0d5e1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast_tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'podcast_tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'podcast_tasks', type_='foreignkey')
    op.drop_column('podcast_tasks', 'user_id')
    # ### end Alembic commands ###
