"""Remove final_script and is_edited from PodcastTask

Revision ID: ce2e9a10b9d0
Revises: ecb497ab0feb
Create Date: 2025-06-28 18:50:48.489419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce2e9a10b9d0'
down_revision: Union[str, Sequence[str], None] = 'ecb497ab0feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tts_results', 'edited_script')
    op.drop_column('tts_results', 'voice')
    op.drop_column('users', 'daily_generation_count')
    op.drop_column('users', 'subscription_plan')
    op.drop_column('users', 'last_generation_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_generation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('subscription_plan', sa.VARCHAR(length=50), server_default=sa.text("'free'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('daily_generation_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('tts_results', sa.Column('voice', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tts_results', sa.Column('edited_script', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
