"""add usage limit and script edit features

Revision ID: ecb497ab0feb
Revises: 7b631d0d5e1c
Create Date: 2025-06-28 18:30:44.038347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb497ab0feb'
down_revision: Union[str, Sequence[str], None] = '7b631d0d5e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tts_results', sa.Column('edited_script', sa.Text(), nullable=True))
    op.add_column('tts_results', sa.Column('voice', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('subscription_plan', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('daily_generation_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_generation_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_generation_date')
    op.drop_column('users', 'daily_generation_count')
    op.drop_column('users', 'subscription_plan')
    op.drop_column('tts_results', 'voice')
    op.drop_column('tts_results', 'edited_script')
    # ### end Alembic commands ###
