services:
  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - 9090:9090
    restart: unless-stopped
    command: --config.file=/etc/mimir.yaml
    volumes:
      - ./services/mimir/mimir.yaml:/etc/mimir.yaml
      - ./services/mimir/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml
 
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - JAEGER_AGENT_HOST=otelcol

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./services/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./services/grafana/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./services/grafana/lgraph-observability-dashboard.json:/etc/grafana/provisioning/dashboards/lgraph-observability-dashboard.json
      - ./services/grafana/lgraph-performance-dashboard.json:/etc/grafana/provisioning/dashboards/lgraph-performance-dashboard.json
      - ./services/grafana/lgraph-error-analysis-dashboard.json:/etc/grafana/provisioning/dashboards/lgraph-error-analysis-dashboard.json
      # - ./services/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki
      - tempo
      - mimir

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "server", "--config.file=/etc/tempo.yaml" ]
    expose:
      - "4317"
    ports:
      - "3200:3200"  # HTTP server (only)
    volumes:
      - ./services/tempo/tempo.yaml:/etc/tempo.yaml

  ## Tools
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/promtail/config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otelcol
    # restart: unless-stopped
    ports:
      - 4317:4317  # otlp grpc
      - 4318:4318  # otlp http
      - 8888:8888 # monitoring
    command: --config=/etc/otelcol/config.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana
    volumes:
      - ./services/otelcol/config.yaml:/etc/otelcol/config.yaml
