version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:17
    container_name: lgraph_postgres
    environment:
      POSTGRES_DB: lgraph
      POSTGRES_USER: lgraph_user
      POSTGRES_PASSWORD: lgraph_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lgraph_network

  # Redis (Celery 브로커)
  redis:
    image: redis:8-alpine
    container_name: lgraph_redis
    ports:
      - "6379:6379"
    networks:
      - lgraph_network

  # MinIO (객체 스토리지)
  minio:
    image: minio/minio:latest
    container_name: lgraph_minio
    ports:
      - "9000:9000"  # API 포트
      - "9001:9001"  # Console 포트
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    networks:
      - lgraph_network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # FastAPI 애플리케이션
  api:
    build: .
    container_name: lgraph_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://lgraph_user:lgraph_password@postgres:5432/lgraph
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AUDIO_STORAGE_PATH=/app/audio_files
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET_NAME=lgraph-audio
      - MINIO_SECURE=false
      - OTEL_EXPORTER_OTLP_ENDPOINT=otelcol:4317
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - .:/app
      - ./audio_files:/app/audio_files  # 음원 파일 저장 볼륨
    networks:
      - lgraph_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker
  celery_worker:
    build: .
    container_name: lgraph_celery_worker
    environment:
      - DATABASE_URL=postgresql+asyncpg://lgraph_user:lgraph_password@postgres:5432/lgraph
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AUDIO_STORAGE_PATH=/app/audio_files
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET_NAME=lgraph-audio
      - MINIO_SECURE=false
      - OTEL_EXPORTER_OTLP_ENDPOINT=otelcol:4317
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - .:/app
      - ./audio_files:/app/audio_files  # 음원 파일 저장 볼륨
    networks:
      - lgraph_network
    command: celery -A celery_app worker --loglevel=info

  # Celery Flower (모니터링)
  celery_flower:
    build: .
    container_name: lgraph_celery_flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - lgraph_network
    command: celery -A celery_app flower --port=5555

volumes:
  postgres_data:
  minio_data:

networks:
  lgraph_network:
    driver: bridge 